Spacing: Add number suffixes to keys
Khan/wonder-blocks pull request #1081
Opened 2020-12-01 21:03 UTC by bryanjclark

This allows developers to use autocomplete, which dramatically simplifies the ergonomics of working with the Spacing component!

This is the same thing we did in mobile back in this PR, and it has been super nice to have:
https://github.com/Khan/mobile/pull/599

This is going to break SO MANY THINGS - so I'd recommend making a second PR that greps for all the Spacing usage and replaces it with these values!

(Another option could be to just add these values to the enum, rather than replacing existing ones?)

2020-12-01 22:35 UTC, kevinbarabash commented
This PR should probably do the renaming as well so that we don't end up with a commit that leaves things in a broken state.  There will need to be a separate diff/PR to update all the places in webapp as well, but that's something I can tackle.

2020-12-01 23:48 UTC, jandrade requested changes
Thanks for tackling this. +1 for what Kevin said about renaming all the instances used inside this repo. 

I think it's definitively better to cover that here, so the website is not broken after merging into `master`. This would include updating Markdown files (used by React Styleguidist) and probably updating snapshot/unit tests.

For reference see the deployed site for this PR: https://deploy-preview-1081--wonder-blocks.netlify.app/

2020-12-01 23:48 UTC, jandrade commented on packages/wonder-blocks-spacing/index.js
> +
I think prettier will complain about this.

2020-12-03 15:56 UTC, kevinbarabash commented on packages/wonder-blocks-clickable/__tests__/__snapshots__/generated-snapshot.test.js.snap
> +        "marginRight": undefined,
Well this is definitely wrong.

2020-12-03 16:54 UTC, jandrade approved these changes
LGTM. Thanks for replacing all the instances!

2020-12-03 18:23 UTC, lillialexis commented
Haha, I was just thinking about this yesterday!

2020-12-03 18:24 UTC, bryanjclark commented
@kevinbarabash would you mind commandeering this one? You've done all the replacements here and I'm happy to resign as driver of this diff!

2020-12-03 21:15 UTC, merged

2020-12-03 21:15 UTC, kevinbarabash commented
@bryanjclark no need for me to commandeer.  It was a collaborative PR. 🙂