Created funky script to scrape roles without manually inputting them
Khan/wonder-blocks pull request #1668
Opened 2022-12-20 23:53 UTC by drewkiimon

## Summary:
<Add your summary here>

Issue: XXX-XXXX

## Test plan:

2022-12-21 17:06 UTC, drewkiimon commented
@jandrade A lot of automated tests here compared to Webapp. Let me know what you think! I put in the script that I used to grab the values.

2022-12-22 15:11 UTC, jandrade commented
@drewkiimon This PR check is failing: https://github.com/Khan/wonder-blocks/actions/runs/3751292386/jobs/6387567301

One reason might be the comment script you added, but I'm not fully sure about it.

2022-12-22 17:21 UTC, jandrade commented
Update: It looks like merging `main` would fix that issue.

2022-12-22 17:26 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +*/
This is great! but I feel this would be better having it in the PR description instead of the code itself.

2022-12-27 16:32 UTC, drewkiimon commented
Thanks for the PR @jandrade ! I removed the comment and put it into this PR instead, and merged `main` into my branch.

2023-01-03 15:58 UTC, jandrade requested changes
Thanks for working on this. Requesting changes to revert some of the lines that were updated and mainly to remove an invalid role (`articles`).

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "articles"
This role `articles` does not exist.

```suggestion
```

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "command"
Could you please leave this line as it was before? I think it's important to state that this is an abstract role and it shouldn't be included in any custom implementation.

`| "command" // abstract role`

> Abstract roles are used for the ontology. Authors MUST NOT use abstract roles in content.

More about it here: https://www.w3.org/TR/wai-aria/#abstract_roles
https://www.w3.org/TR/wai-aria/#isAbstract

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "composite"
Same here:

```suggestion
    | "composite" // abstract role
```

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "landmark"
Here too... `... // abstract role`.

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "range"
same here: 
```suggestion
    | "range" // abstract role
```

2023-01-03 15:58 UTC, jandrade commented on packages/wonder-blocks-core/src/util/types.js
> +    | "roletype"
```suggestion
    | "roletype" // abstract role
```

2023-03-06 17:15 UTC, kevinbarabash commented
This is superseded by #1780.  It uses React's `AriaRole` type.  Please note that that type does not include abstract roles like `landmark`, but it does allow any string to be use.  See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L1741-L1811 for the full definition of the `AriaRole`.

2023-03-06 17:15 UTC, closed without merging